require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

Documentation:
  Enabled: false

LineLength:
  Max: 99

FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
